/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets/{representation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Asset */
        get: operations["get_asset_api_v1_assets__representation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Head Asset */
        head: operations["head_asset_api_v1_assets__representation_id__head"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Artifacts */
        get: operations["query_artifacts_api_v1_catalog_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/artifacts/{artifact_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artifact */
        get: operations["get_artifact_api_v1_catalog_artifacts__artifact_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/artifacts/{artifact_id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Manifest */
        get: operations["get_manifest_api_v1_catalog_artifacts__artifact_id__manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Head Manifest */
        head: operations["head_manifest_api_v1_catalog_artifacts__artifact_id__manifest_head"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/artifacts/{artifact_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sources */
        get: operations["get_sources_api_v1_catalog_artifacts__artifact_id__sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/captures/{capture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capture */
        get: operations["get_capture_api_v1_catalog_captures__capture_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v1_catalog_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Alignment */
        Alignment: {
            /** Clock Offset S */
            clock_offset_s?: number | null;
            /** Clock Peak Quality */
            clock_peak_quality?: number | null;
            /**
             * Gravity Constrained
             * @default false
             */
            gravity_constrained: boolean;
            /** Horizontal Rmse M */
            horizontal_rmse_m?: number | null;
            /** Inlier Count */
            inlier_count: number;
            /** Method */
            method: string;
            /** Model To Artifact Local */
            model_to_artifact_local: number[];
            /** Rejection Reason */
            rejection_reason?: string | null;
            /** Scale */
            scale: number;
            status: components["schemas"]["AlignmentStatus"];
            /** Vertical Rmse M */
            vertical_rmse_m?: number | null;
        };
        /**
         * AlignmentStatus
         * @enum {string}
         */
        AlignmentStatus: "unaligned" | "approximate" | "aligned" | "reviewed";
        /** ArtifactDetail */
        ArtifactDetail: {
            alignment_status: components["schemas"]["AlignmentStatus"];
            /** Artifact Id */
            artifact_id: string;
            /** Capture Id */
            capture_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            footprint?: components["schemas"]["GeoJSONPolygon"] | null;
            /** Frame Name */
            frame_name: string;
            /** Kind */
            kind: string;
            layer_default?: components["schemas"]["LayerDefault"] | null;
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Point Count */
            point_count?: number | null;
            /** Representations */
            representations: components["schemas"]["RepresentationResponse"][];
            /** Run Id */
            run_id: string;
            /** Units */
            units: string;
        };
        /** ArtifactFile */
        ArtifactFile: {
            /** Bounds Max */
            bounds_max?: [
                number,
                number,
                number
            ] | null;
            /** Bounds Min */
            bounds_min?: [
                number,
                number,
                number
            ] | null;
            /** Byte Size */
            byte_size: number;
            /** Columns */
            columns?: components["schemas"]["ColumnContract"][];
            /** Format */
            format: string;
            /** Frame */
            frame?: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "points" | "mesh" | "splats" | "poses" | "telemetry_gps" | "telemetry_imu" | "sources" | "metrics" | "raw";
            /** Media Type */
            media_type: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Path */
            path: string;
            /** Point Count */
            point_count?: number | null;
            /** Representation Id */
            representation_id: string;
            /** Required Dimensions */
            required_dimensions?: string[];
            /** Sha256 */
            sha256: string;
        };
        /** ArtifactSummary */
        ArtifactSummary: {
            alignment_status: components["schemas"]["AlignmentStatus"];
            /** Artifact Id */
            artifact_id: string;
            /** Capture Id */
            capture_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            footprint?: components["schemas"]["GeoJSONPolygon"] | null;
            /** Frame Name */
            frame_name: string;
            /** Kind */
            kind: string;
            /** Point Count */
            point_count?: number | null;
            /** Run Id */
            run_id: string;
            /** Units */
            units: string;
        };
        /** CaptureMetadata */
        CaptureMetadata: {
            /** Device */
            device?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Fps */
            fps?: number | null;
            /** Frame Count */
            frame_count?: number | null;
            /** Gps Sample Count */
            gps_sample_count?: number | null;
            /** Imu Sample Count */
            imu_sample_count?: number | null;
            /** Lens */
            lens?: string | null;
            /** Source Uri */
            source_uri?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Video Name */
            video_name?: string | null;
        };
        /** CaptureResponse */
        CaptureResponse: {
            /** Capture Id */
            capture_id: string;
            /** Device */
            device?: string | null;
            /** Ended At */
            ended_at?: string | null;
            footprint?: components["schemas"]["GeoJSONPolygon"] | null;
            /** Fps */
            fps?: number | null;
            /** Frame Count */
            frame_count?: number | null;
            /** Lens */
            lens?: string | null;
            /** Source Uri */
            source_uri?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Video Name */
            video_name?: string | null;
        };
        /** CatalogArtifactsResponse */
        CatalogArtifactsResponse: {
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactSummary"][];
            /** Count */
            count: number;
        };
        /** ColumnContract */
        ColumnContract: {
            /** Dtype */
            dtype: string;
            /** Name */
            name: string;
            /**
             * Nullable
             * @default false
             */
            nullable: boolean;
            /** Unit */
            unit?: string | null;
        };
        /** CoordinateFrame */
        CoordinateFrame: {
            /** Axis Order */
            axis_order: string[];
            /** Crs */
            crs?: string | null;
            /**
             * Handedness
             * @enum {string}
             */
            handedness: "right" | "left" | "unknown";
            /**
             * Name
             * @default artifact_local
             */
            name: string;
            /** Origin Wgs84 */
            origin_wgs84?: [
                number,
                number,
                number
            ] | null;
            /** Pose Convention */
            pose_convention?: string | null;
            /** Proj Pipeline */
            proj_pipeline?: string | null;
            /** Transform To Ecef */
            transform_to_ecef?: number[] | null;
            /**
             * Units
             * @enum {string}
             */
            units: "metre" | "unknown";
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string | {
                [key: string]: unknown;
            }[];
        };
        /** GeoJSONPolygon */
        GeoJSONPolygon: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][];
            /**
             * Type
             * @constant
             */
            type: "Polygon";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Catalog */
            catalog: string;
            /**
             * Status
             * @constant
             */
            status: "healthy";
        };
        /** LayerDefault */
        LayerDefault: {
            /** Color Dimension */
            color_dimension?: string | null;
            /**
             * Opacity
             * @default 1
             */
            opacity: number;
            /** Point Budget */
            point_budget?: number | null;
            /** Point Size */
            point_size?: number | null;
            /**
             * Visible
             * @default true
             */
            visible: boolean;
        };
        /** LossyOperation */
        LossyOperation: {
            /** Operation */
            operation: string;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            };
            /** Points In */
            points_in?: number | null;
            /** Points Out */
            points_out?: number | null;
            /** Provenance Policy */
            provenance_policy?: string | null;
        };
        /** Manifest */
        Manifest: {
            alignment: components["schemas"]["Alignment"];
            /** Artifact Id */
            artifact_id: string;
            /** Artifacts */
            artifacts: components["schemas"]["ArtifactFile"][];
            capture: components["schemas"]["CaptureMetadata"];
            /** Capture Id */
            capture_id: string;
            coordinate_frame: components["schemas"]["CoordinateFrame"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            footprint_wgs84?: components["schemas"]["WGS84Footprint"] | null;
            layer_default?: components["schemas"]["LayerDefault"] | null;
            /** Lossy Operations */
            lossy_operations?: components["schemas"]["LossyOperation"][];
            producer: components["schemas"]["Producer"];
            /** Run Id */
            run_id: string;
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
        };
        /** Producer */
        Producer: {
            /** Adapter Name */
            adapter_name: string;
            /** Adapter Version */
            adapter_version: string;
            /** Capabilities */
            capabilities?: {
                [key: string]: boolean;
            };
            /** Git Commit */
            git_commit?: string | null;
            /**
             * Git Status
             * @default unknown
             * @enum {string}
             */
            git_status: "clean" | "dirty" | "unknown";
            /** Model Config */
            model_config?: {
                [key: string]: unknown;
            };
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version?: string | null;
            /** Publisher Name */
            publisher_name: string;
            /** Publisher Version */
            publisher_version: string;
        };
        /** RepresentationResponse */
        RepresentationResponse: {
            /** Asset Url */
            asset_url: string;
            /** Byte Size */
            byte_size: number;
            /** Format */
            format: string;
            /** Kind */
            kind: string;
            /** Media Type */
            media_type: string;
            /** Relative Path */
            relative_path: string;
            /** Representation Id */
            representation_id: string;
            /** Sha256 */
            sha256: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Capture Id */
            capture_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Git Commit */
            git_commit?: string | null;
            /**
             * Git Status
             * @enum {string}
             */
            git_status: "clean" | "dirty" | "unknown";
            /** Manifest Sha256 */
            manifest_sha256: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version?: string | null;
            /** Run Id */
            run_id: string;
            status: components["schemas"]["AlignmentStatus"];
        };
        /** SourceRecord */
        SourceRecord: {
            /** Capture Id */
            capture_id: string;
            /** Frame End */
            frame_end?: number | null;
            /** Frame Indices */
            frame_indices?: number[] | null;
            /** Frame Start */
            frame_start?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "window" | "submap" | "keyframe_group" | "batch" | "capture";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Name */
            name?: string | null;
            /** Point Count */
            point_count?: number | null;
            /** Run Id */
            run_id: string;
            /** Source Index */
            source_index: number;
            /** Timestamp End S */
            timestamp_end_s?: number | null;
            /** Timestamp Start S */
            timestamp_start_s?: number | null;
        };
        /** SourcesResponse */
        SourcesResponse: {
            /** Count */
            count: number;
            /** Sources */
            sources: components["schemas"]["SourceRecord"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WGS84Footprint
         * @description A single exterior WGS84 ring, in longitude/latitude order.
         */
        WGS84Footprint: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_asset_api_v1_assets__representation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                representation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Requested representation byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Representation ETag matched */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested range is not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_asset_api_v1_assets__representation_id__head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                representation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_artifacts_api_v1_catalog_artifacts_get: {
        parameters: {
            query?: {
                bbox?: string | null;
                started_after?: string | null;
                ended_before?: string | null;
                alignment_status?: components["schemas"]["AlignmentStatus"] | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogArtifactsResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_artifact_api_v1_catalog_artifacts__artifact_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_manifest_api_v1_catalog_artifacts__artifact_id__manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
            /** @description Requested manifest byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Manifest ETag matched */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested range is not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    head_manifest_api_v1_catalog_artifacts__artifact_id__manifest_head: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Requested manifest byte range */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Manifest ETag matched */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Requested range is not satisfiable */
            416: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sources_api_v1_catalog_artifacts__artifact_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capture_api_v1_catalog_captures__capture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_catalog_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
